module.exports = function(sequelize, DataTypes) {
  var pokedex = sequelize.define("pokedex", {
    abilities: DataTypes.STRING,
    against_bug: DataTypes.DECIMAL(11,2),
    against_dark: DataTypes.DECIMAL(11,2),
    against_dragon: DataTypes.DECIMAL(11,2),
    against_electric: DataTypes.DECIMAL(11,2),
    against_fairy: DataTypes.DECIMAL(11,2),
    against_fight: DataTypes.DECIMAL(11,2),
    against_fire: DataTypes.DECIMAL(11,2),
    against_flying: DataTypes.DECIMAL(11,2),
    against_ghost: DataTypes.DECIMAL(11,2),
    against_grass: DataTypes.DECIMAL(11,2),
    against_ground: DataTypes.DECIMAL(11,2),
    against_ice: DataTypes.DECIMAL(11,2),
    against_normal: DataTypes.DECIMAL(11,2),
    against_poison: DataTypes.DECIMAL(11,2),
    against_psychic: DataTypes.DECIMAL(11,2),
    against_rock: DataTypes.DECIMAL(11,2),
    against_steel: DataTypes.DECIMAL(11,2),
    against_water: DataTypes.DECIMAL(11,2),
    attack: DataTypes.INTEGER,
    base_egg_steps: DataTypes.INTEGER,
    base_happiness: DataTypes.INTEGER,
    base_total: DataTypes.INTEGER,
    capture_rate: DataTypes.INTEGER,
    classfication: DataTypes.TEXT,
    defense:DataTypes.INTEGER,
    experience_growth: DataTypes.INTEGER,
    height_m: DataTypes.DECIMAL(11,2),
    hp:DataTypes.INTEGER,
    japanese_name:DataTypes.STRING,
    name:DataTypes.STRING,
    percentage_male:DataTypes.DECIMAL(11,2),
    pokedex_number:DataTypes.INTEGER,
    sp_attack: DataTypes.INTEGER,
    sp_defense: DataTypes.INTEGER,
    speed: DataTypes.INTEGER,
    type1: DataTypes.STRING,
    type2: DataTypes.STRING,
    weight_kg:DataTypes.DECIMAL(11,2),
    generation: DataTypes.INTEGER,
    is_legendary: DataTypes.BOOLEAN
    
  });
  return pokedex;
};
